module VerifyExamples.Model.Date.Compare1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Date exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#compare: \n\n    Model.Date.compare (onlyYear 2020) (full 2020 Dec)\n    --> GT" <|
        \() ->
            Expect.equal
                (
                Model.Date.compare (onlyYear 2020) (full 2020 Dec)
                )
                (
                GT
                )