module VerifyExamples.Model.Date.Compare5 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Date exposing (..)







spec5 : Test.Test
spec5 =
    Test.test "#compare: \n\n    Model.Date.compare (full 2020 Jan) (full 2021 Jan)\n    --> LT" <|
        \() ->
            Expect.equal
                (
                Model.Date.compare (full 2020 Jan) (full 2021 Jan)
                )
                (
                LT
                )