module VerifyExamples.Model.Date.MonthsBetween0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Date exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#monthsBetween: \n\n    monthsBetween (onlyYear 2020) (onlyYear 2022)\n    --> Just 24" <|
        \() ->
            Expect.equal
                (
                monthsBetween (onlyYear 2020) (onlyYear 2022)
                )
                (
                Just 24
                )