module VerifyExamples.Model.Date.MonthsBetweenMonths2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Date exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#monthsBetweenMonths: \n\n    monthsBetweenMonths Jan Jan\n    --> 0" <|
        \() ->
            Expect.equal
                (
                monthsBetweenMonths Jan Jan
                )
                (
                0
                )