module VerifyExamples.Model.Date.MonthsBetween7 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Date exposing (..)







spec7 : Test.Test
spec7 =
    Test.test "#monthsBetween: \n\n    monthsBetween (full 2020 Mar) (full 2020 Jan)\n    --> Just 2" <|
        \() ->
            Expect.equal
                (
                monthsBetween (full 2020 Mar) (full 2020 Jan)
                )
                (
                Just 2
                )