module VerifyExamples.Model.Date.MonthsBetweenMonths0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Date exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#monthsBetweenMonths: \n\n    monthsBetweenMonths Apr Jan\n    --> 3" <|
        \() ->
            Expect.equal
                (
                monthsBetweenMonths Apr Jan
                )
                (
                3
                )