module VerifyExamples.Model.Event.Category.Set1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Event.Category exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#set: \n\n    allSelected |> set Academic False |> isEventCategorySelected Academic\n    --> False" <|
        \() ->
            Expect.equal
                (
                allSelected |> set Academic False |> isEventCategorySelected Academic
                )
                (
                False
                )