module VerifyExamples.Model.Interval.Compare4 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Interval exposing (..)
import Model.Date as Date







spec4 : Test.Test
spec4 =
    Test.test "#compare: \n\n    Model.Interval.compare (oneYear 2019) (oneYear 2020)\n    --> LT" <|
        \() ->
            Expect.equal
                (
                Model.Interval.compare (oneYear 2019) (oneYear 2020)
                )
                (
                LT
                )