module VerifyExamples.Model.Interval.Compare2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Interval exposing (..)
import Model.Date as Date







spec2 : Test.Test
spec2 =
    Test.test "#compare: \n\n    Model.Interval.compare (withDurationMonths 2019 Date.Jan 2) (withDurationMonths 2019 Date.Jan 2)\n    --> EQ" <|
        \() ->
            Expect.equal
                (
                Model.Interval.compare (withDurationMonths 2019 Date.Jan 2) (withDurationMonths 2019 Date.Jan 2)
                )
                (
                EQ
                )