module VerifyExamples.Model.Interval.Compare1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Interval exposing (..)
import Model.Date as Date







spec1 : Test.Test
spec1 =
    Test.test "#compare: \n\n    Model.Interval.compare (withDurationMonths 2019 Date.Feb 2) (withDurationMonths 2019 Date.Jan 2)\n    --> GT" <|
        \() ->
            Expect.equal
                (
                Model.Interval.compare (withDurationMonths 2019 Date.Feb 2) (withDurationMonths 2019 Date.Jan 2)
                )
                (
                GT
                )