module VerifyExamples.Model.Interval.Compare0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Interval exposing (..)
import Model.Date as Date







spec0 : Test.Test
spec0 =
    Test.test "#compare: \n\n    Model.Interval.compare (withDurationMonths 2019 Date.Jan 2) (open (Date.onlyYear 2019))\n    --> LT" <|
        \() ->
            Expect.equal
                (
                Model.Interval.compare (withDurationMonths 2019 Date.Jan 2) (open (Date.onlyYear 2019))
                )
                (
                LT
                )