module VerifyExamples.Model.Interval.Compare3 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Model.Interval exposing (..)
import Model.Date as Date







spec3 : Test.Test
spec3 =
    Test.test "#compare: \n\n    Model.Interval.compare (oneYear 2019) (withDurationYears (Date.onlyYear 2020) 2)\n    --> LT" <|
        \() ->
            Expect.equal
                (
                Model.Interval.compare (oneYear 2019) (withDurationYears (Date.onlyYear 2020) 2)
                )
                (
                LT
                )